## Model fits per trial 

```{r}
load("../processed/data.ev-final.RData", verbose = T)

ex = "in"
dataall 				<- data.ev
dataall$id              <- as.numeric(as.character(dataall$id))
dataall$bandit_real_id  <- as.numeric(as.character(dataall$bandit_real_id))
dataall$payoff          <- as.numeric(as.character(dataall$payoff))
dataall$ev              <- as.numeric(as.character(dataall$ev))
dataall <- dataall[, c("id", "bandit_real_id", "payoff", "trial_number", 
					   "block_id", "ev", "block_size", "age_group")]

BB.LB = c(0.005) # theta
BB.UB = c(30)    # theta
MAXITERBB = 1
WHLEBB = 10 # should be 10 or so
MAX_CHOICESB = 100 # should be 100
MIN_GRAIN = 1000
INITQ = 0
```

```{r, eval=T}
source("optimfunctions.R", verbose = T)
source("plotfunctions.R", verbose = T)
```


### 4 options

```{r}
N_BANDITS = 4
```


```{r, eval=F}
group = "young"
data <- dataall[dataall$block_size == N_BANDITS,]
data <- data[data$age_group == group,]

fits <- getParams(data)
preds <- getPredictions(data, fits)

filename = paste("../processed/BBresults", N_BANDITS, "N", group, ex, ".RData", sep= "")
save('fits', 'preds', file=filename)
```


```{r, eval=F}
group = "old"
data <- dataall[dataall$block_size == N_BANDITS,]
data <- data[data$age_group == group,]

fits <- getParams(data)
preds <- getPredictions(data, fits)

filename = paste("../processed/BBresults", N_BANDITS, "N", group, ex, ".RData", sep= "")
save('fits', 'preds', file=filename)
```


```{r child = 'plotOptim.Rmd'}
```

\newpage 


### 8 options

```{r}
N_BANDITS = 8
```


```{r, eval=F}
group = "young"
data <- dataall[dataall$block_size == N_BANDITS,]
data <- data[data$age_group == group,]

fits <- getParams(data)
preds <- getPredictions(data, fits)

filename = paste("../processed/BBresults", N_BANDITS, "N", group, ex, ".RData", sep= "")
save('fits', 'preds', file=filename)
```


```{r, eval=F}
group = "old"
data <- dataall[dataall$block_size == N_BANDITS,]
data <- data[data$age_group == group,]

fits <- getParams(data)
preds <- getPredictions(data, fits)

filename = paste("../processed/BBresults", N_BANDITS, "N", group, ex, ".RData", sep= "")
save('fits', 'preds', file=filename)
```


```{r child = 'plotOptim.Rmd'}
```

\newpage


